import { Invoice } from '../../types'

// Temporary mock data. TODO: remove
const mockInvoices: Partial<Invoice>[] = [
  {
    invoiceId: '1',
    invoiceNumber: '2022/546',
    created: new Date(),
    sent: new Date(),
    paid: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepe',
    clientAddress: 'some address',
    services: [],
    status: 'PENDING',
    costAmount: '4 EUR',
    totalAmount: '4 EUR',
    applicableTaxRate: '',
  },
  {
    invoiceId: '2',
    invoiceNumber: '2022/547',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 2',
    costAmount: '5 EUR',
    totalAmount: '5 EUR',
    status: 'PENDING',
    draft: true,
  },
  {
    invoiceId: '3',
    invoiceNumber: '2022/548',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 3',
    costAmount: '6 EUR',
    totalAmount: '6 EUR',
    status: 'PENDING',
    draft: true,
  },
  {
    invoiceId: '4',
    invoiceNumber: '2022/549',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 4',
    costAmount: '7 EUR',
    totalAmount: '7 EUR',
    status: 'PENDING',
    draft: true,
  },
  {
    invoiceId: '5',
    invoiceNumber: '2022/550',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 5',
    costAmount: '8 EUR',
    totalAmount: '8 EUR',
    status: 'PENDING',
  },
  {
    invoiceId: '6',
    invoiceNumber: '2022/551',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 6',
    costAmount: '9 EUR',
    totalAmount: '9 EUR',
    status: 'PAID',
    draft: true,
  },
  {
    invoiceId: '7',
    invoiceNumber: '2022/552',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 7',
    costAmount: '10 EUR',
    totalAmount: '10 EUR',
    status: 'PAID',
    draft: true,
  },
  {
    invoiceId: '8',
    invoiceNumber: '2022/553',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 8',
    costAmount: '11 EUR',
    totalAmount: '11 EUR',
    status: 'PAID',
  },
  {
    invoiceId: '9',
    invoiceNumber: '2022/554',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 9',
    costAmount: '12 EUR',
    totalAmount: '12 EUR',
    status: 'PAID',
  },
  {
    invoiceId: '10',
    invoiceNumber: '2022/555',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 10',
    costAmount: '13 EUR',
    totalAmount: '13 EUR',
    status: 'SENT',
  },
  {
    invoiceId: '11',
    invoiceNumber: '2022/556',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 11',
    costAmount: '14 EUR',
    totalAmount: '14 EUR',
    status: 'SENT',
  },
  {
    invoiceId: '12',
    invoiceNumber: '2022/557',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 12',
    costAmount: '15 EUR',
    totalAmount: '15 EUR',
    status: 'SENT',
  },
  {
    invoiceId: '13',
    invoiceNumber: '2022/558',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 13',
    costAmount: '16 EUR',
    totalAmount: '16 EUR',
    status: 'CANCELLED',
  },
  {
    invoiceId: '14',
    invoiceNumber: '2022/559',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 14',
    costAmount: '17 EUR',
    totalAmount: '17 EUR',
    status: 'CANCELLED',
  },
  {
    invoiceId: '15',
    invoiceNumber: '2022/560',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 15',
    costAmount: '18 EUR',
    totalAmount: '18 EUR',
    status: 'CANCELLED',
  },
  {
    invoiceId: '16',
    invoiceNumber: '2022/561',
    created: new Date(),
    costAmount: '19 EUR',
    totalAmount: '19 EUR',
    status: 'CANCELLED',
  },
  {
    invoiceId: '17',
    invoiceNumber: '2022/562',
    created: new Date(),
    clientEmail: 'blabla@gmail.com',
    clientName: 'Pepita María 17',
    costAmount: '20 EUR',
    totalAmount: '20 EUR',
    status: 'CANCELLED',
  },
]

export { mockInvoices }
