import { Client } from '../../types'

const mockClients: Partial<Client>[] = [
  { clientId: '1', clientType: 'individual', name: 'pepe', email: 'email a', phone: 'phone', notes: 'notes' },
  { clientId: '2', clientType: 'individual', name: 'pepa', email: 'email b', phone: 'phone', notes: 'notes' },
  {
    clientId: '3',
    clientType: 'individual',
    name: 'ramón',
    email: 'email c',
    phone: 'phone',
    notes: 'notes',
  },
  {
    clientId: '4',
    clientType: 'individual',
    name: 'sergio',
    email: 'email d',
    phone: 'phone',
    notes: 'notes',
  },
  { clientId: '5', clientType: 'individual', name: 'edu', email: 'email e', phone: 'phone', notes: 'notes' },
  { clientId: '6', clientType: 'individual', name: 'emi', email: 'email f', phone: 'phone', notes: 'notes' },
  { clientId: '7', clientType: 'individual', name: 'cris', email: 'email g', phone: 'phone', notes: 'notes' },
  { clientId: '8', clientType: 'individual', name: 'inma', email: 'email h', phone: 'phone', notes: 'notes' },
  {
    clientId: '9',
    clientType: 'individual',
    name: 'blanca',
    email: 'email i',
    phone: 'phone',
    notes: 'notes',
  },
  { clientId: '10', clientType: 'individual', name: 'isa', email: 'email j', phone: 'phone', notes: 'note' },
  {
    clientId: '11',
    clientType: 'individual',
    name: 'pedro',
    email: 'email k',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '12',
    clientType: 'individual',
    name: 'antonio',
    email: 'email l',
    phone: 'phone',
    notes: 'note',
  },
  { clientId: '13', clientType: 'individual', name: 'javi', email: 'email m', phone: 'phone', notes: 'note' },
  { clientId: '14', clientType: 'individual', name: 'juan', email: 'email n', phone: 'phone', notes: 'note' },
  {
    clientId: '15',
    clientType: 'individual',
    name: 'carlos',
    email: 'email o',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '16',
    clientType: 'individual',
    name: 'pilar',
    email: 'email p',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '17',
    clientType: 'individual',
    name: 'laura',
    email: 'email q',
    phone: 'phone',
    notes: 'note',
  },
  { clientId: '18', clientType: 'individual', name: 'cris', email: 'email r', phone: 'phone', notes: 'note' },
  {
    clientId: '19',
    clientType: 'individual',
    name: 'diego',
    email: 'email s',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '20',
    clientType: 'individual',
    name: 'claudio',
    email: 'email t',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '21',
    clientType: 'individual',
    name: 'conchita',
    email: 'email u',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '22',
    clientType: 'individual',
    name: 'manolo',
    email: 'email w',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '23',
    clientType: 'individual',
    name: 'aurora',
    email: 'email x',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '24',
    clientType: 'individual',
    name: 'felipe',
    email: 'email y',
    phone: 'phone',
    notes: 'note',
  },
  { clientId: '25', clientType: 'individual', name: 'rosa', email: 'email z', phone: 'phone', notes: 'note' },
  {
    clientId: '26',
    clientType: 'individual',
    name: 'alberto',
    email: 'email 0',
    phone: 'phone',
    notes: 'note',
  },
  {
    clientId: '27',
    clientType: 'individual',
    name: 'juanjo',
    email: 'email 1',
    phone: 'phone',
    notes: 'note',
  },
]

export { mockClients }
